unityのonload時まで、コードを実行できないようにする
CodeParty2021/code_party_front pull request #104
Opened 2022-08-01 07:34 UTC by TAKUMI-TAKAMATU

# やったこと
コーディング画面でunityがローディング中にボタンを押して実行できないようにしました

# 確認して欲しいこと
以下のチケットを参考に確認お願いします
https://www.notion.so/063ef9879cfc4e37aa705e44558bd099?p=e401078bae3c4c09b5c43f4b719a8527&pm=s

2022-08-01 08:41 UTC, iikyara requested changes
動作は完璧でした！！
変数名が今までcamelCaseで統一してきたので、camelCaseで書いてほしいです！
お願いしますー！

2022-08-01 08:41 UTC, iikyara commented on src/pages/Code/Coding/Coding.tsx
> +    unityload,
camelCaseで頼んだ！

2022-08-01 08:41 UTC, iikyara commented on src/pages/Code/Coding/hooks/useCodeHooks.tsx
> +  unityload: boolean;
camelCaseで頼んだ！

2022-08-01 08:41 UTC, iikyara commented on src/pages/Code/Coding/hooks/useCodeHooks.tsx
> +  const [unityload, setunityload] = useState<boolean>(true);
camelCaseで頼んだ！

2022-08-01 08:41 UTC, iikyara commented on src/pages/Code/Coding/hooks/useCodeHooks.tsx
> +      setunityload(false);
camelCaseで頼んだ！

2022-08-01 08:41 UTC, iikyara commented on src/pages/Code/Coding/hooks/useCodeHooks.tsx
> +    unityload,
camelCaseで頼んだ！

2022-08-01 08:59 UTC, TAKUMI-TAKAMATU commented
CamelCaseに修正しました！

2022-08-01 09:20 UTC, iikyara commented
なんかNetlifyでエラー出てるな
もう一回ビルドしてみるわ

2022-08-04 06:38 UTC, iikyara approved these changes
確認した！大丈夫やと思う！LGTMー！

2022-08-04 08:32 UTC, merged