フリーコーディングの分割
CodeParty2021/code_party_front pull request #118
Opened 2022-10-27 11:35 UTC by iikyara

# やったこと
- フリーコーディングを分割しました
- フリーコーディングページのロジックをリファクタリング
  - useCode: コードの状態を扱うロジック
  - useResult: シミュレーション結果を扱うロジック
  - useMonacoEditor: MonacoEditorを扱うロジック
  - useUnityGame: Unityを扱うロジック
  - useDummyLoading: ダミーロードを行うロジック

2022-11-14 14:55 UTC, teruto725 commented
力尽きたのでここまで

2022-11-15 05:17 UTC, teruto725 commented
[疑問点]
src/pages/Code/Coding/CodingStyle.tsx 138目のflexGapが何してるのか気になる。

2022-11-15 05:21 UTC, iikyara commented
> [疑問点]
> 
> src/pages/Code/Coding/CodingStyle.tsx 138目のflexGapが何してるのか気になる。

UnityコンポーネントとWatchingLogoコンポーネントを縦に並べた時の隙間を指定してる

2022-11-17 06:02 UTC, teruto725 requested changes
一通り見終わったと思う！
レビューしていて感じる大変さ、お疲れ様です！！
タグを付けてるので[提案],[質問]らへんは見てもらえると嬉しいです！

2022-12-18 07:17 UTC, iikyara commented on src/hooks/DummyLoadingHooks/useDummyLoading.tsx
> +  loadTime: 1000,
これは返してるんじゃなくて内部状態やな
返しているのはこっち
```
export type IResponse = {
  /**
   * コードの状態
   */
  dummyLoadingState: DummyLoadingState;
  /**
   * ロードを開始する
   */
  startDummyLoad: () => Promise<void>;
};
```

2022-12-18 07:24 UTC, iikyara commented on src/hooks/DummyLoadingHooks/useDummyLoading.tsx
> +  }, []);
_setIsLoading関数を使いたいので、メモは使えないと思う
フック内のいろんな関数からisLoadingだけ書き換える役割
云わばセッターメソッド

2022-12-18 07:33 UTC, iikyara commented on src/hooks/CodeHooks/useCode.ts
> +  ) => Promise<string>;
typescriptとDDDは相性良いかもしれないけど、使いすぎるとわけわからなくなりそうと思った
codeIdって結局number?string?みたいなのがわからない（カーソル合わせても表示されないので、結局型ファイルを読みに行く羽目になる）
あと、現状codeIdが文字列の時と数字の時があるからそれもどこかで統一したいね

PS. DDD対応はでかいPRになると思うからこのPRでは考えたくないです...

2022-12-18 07:37 UTC, iikyara commented on src/hooks/CodeHooks/useCode.ts
> +        "def select(field,my_pos,other_pos):\n  return 0",
それできない気がする
以下ができる場合
```
const hoge = ({a: number, b: string}) => {}

hoge({a: 1, b: "fuga"});
```

以下ができない場合（オブジェクトで引数を指定しないとできない）
```
const hoge = (a: number, b: string) => {}

hoge(a: 1, b: "fuga"); // -> error
```

2022-12-18 07:51 UTC, iikyara commented on src/pages/Code/Coding/hooks/useCodeHooks.tsx
> +    reset();
resultがロードされたら（存在していたら）UnityGame画面に移動するという制御にしているので、エディタ画面に戻る際にresultをリセットする必要がある感じです。

2022-12-18 07:54 UTC, iikyara commented on src/pages/Code/Coding/hooks/useCodeHooks.tsx
> +  const error = useMemo(() => resultState.isFailed, [resultState.isFailed]);
可読性のために残したけど、resultState.isFailedをそのまま使ったほうが可読性高そうやな
修正します

2022-12-18 07:56 UTC, iikyara commented on src/hooks/CodeAPIHooks/useCodeAPI.ts
> +          }
型ガードはしなくてもいいけど、そんなに処理重くないし仕様変更に強くなるから入れるようにしている
どれぐらいチェックするかは人による気がするな
ルール作っても良いし作らなくても良い感じがある
ちなみに、僕の知識では型チェックはこれ以上便利にはできないです（型情報はコンパイルされないので）

2022-12-18 08:11 UTC, iikyara commented on src/pages/Code/Coding/hooks/useCodeHooks.tsx
> +    if (codeState && codeState.isExecutable) {
ここのロジックの切り分けが分らんのよね
２重実装を避けるためには以下の２通り
- useCodeの方にガード節を入れる場合
  - useCodeHooks側ではガード節がいらないが、UIの制御をする必要があるので結局条件は必要
- useCodeの方にガード節を入れない場合
  - useCodeHooks側でUIの制御をしてガードできるが、ガードの実装を忘れるとロジックが崩れる可能性がある

理想はこんな感じやろか？（意見お願いします）
- useCodeの方にガード節を配置（ロジックの統一）
- useCodeHooksではUIの状態変化だけに状態を使う
  - ロジックの実装はしない（入力チェックしない）

2022-12-18 08:29 UTC, iikyara commented on src/hooks/ResultHooks/useResult.ts
> +  const testCode = useCallback<IResponse["testCode"]>(async (codeState) => {
なんならコードIDしか使ってないからコードIDだけ渡すように修正した
まあ、責務はUIに持たせたらよさそう
現状はボタンの状態がその責務を負う感じかな？

2022-12-18 08:37 UTC, iikyara commented on src/hooks/CodeHooks/useCode.ts
> +  isLoading: boolean;
僕はloadingはhooksで管理する派
loadingをページ側で管理すると、そのフックを使うたびにページの状態が増えてしまうため（何度も同じloading実装が現れてしまう）

> Loadingはどちらかというと描画よりの話なので、ロジック側のHooksで実装したくない

ロード中は確かに描画されるが、ロード中もロジックの一部だと思っている
ロード中という概念がないとリソースが存在するかどうかのロジックを組めないため

2022-12-18 08:38 UTC, iikyara commented on src/hooks/CodeHooks/useCode.ts
> +  isSave: boolean;
保存エラー的なのがあるかと思って実装した
UIに保存できませんでしたを表示したい場合など

2022-12-18 08:43 UTC, iikyara commented on src/hooks/CodeHooks/useCode.ts
> +  );
エラーの処理はちょっと難しい話になりそうなので議論リストに入れたい

> stateで持つとしてもその理由は例えば「フロント上でエラーが発生しているときはボタンを押せなくする」みたいなかなり描画寄りの都合な気がしていてPageHooks側の責務になるのが正しい気がする。

ここらへんも、pageHooksに実装すると、同じエラー処理とかエラーの種類をいろんな箇所で実装することになりそうで微妙
すべてのエラーの種類を一括で定義して、ページ側でキャッチするようなフックを作るとかなら全然あり
これならエラーをフックから切り離せそう？

2022-12-18 08:43 UTC, iikyara commented on src/hooks/CodeHooks/useCode.ts
> +  isOnline: boolean;
codeリソースはオンライン上に存在しないとtestを実行できないので、そのステータス用の状態
ただ、現状はあまり機能してなさそう？

2022-12-20 16:11 UTC, teruto725 approved these changes
大まかに問題なさそうなのでLGTMで！

ちょっと今回コメント頑張ってみたけど、
どうだったかまたdiscusstionしたい。

2022-12-20 16:14 UTC, teruto725 commented
loadingだけ起票しました！
https://www.notion.so/Loading-0f566eaf61824a30847d41516bdad1e9

2022-12-20 23:49 UTC, merged