[wip]スタートページの実装
CodeParty2021/code_party_front pull request #123
Opened 2022-11-19 08:23 UTC by teruto725

2023-01-05 13:34 UTC, iikyara requested changes
netlifyプレビューだとTwitterとFacebookのログイン（とメールアドレスログイン）が動いてないな
FirebaseのAuthentication methodにTwitterとFacebookを追加すれば多分動きそう！
メールアドレスログインはフォームが必要だから一旦非表示でいいと思う（デザインもない？気がするし）
あと、コンフリクト解消お願いします！

2023-01-05 13:34 UTC, iikyara commented on src/pages/Start/Start.tsx
> +    { service: "email", Icon: Mail, text: "メールアドレスでログイン" },
メールアドレスのログインができないので、一旦非表示にしておく？
メールアドレスログインを実装しようと思うと、多分自前でフォームを作る必要があると思う

2023-01-05 13:34 UTC, iikyara commented on src/pages/RoomMatch/Invitation/Invitation.tsx
> +    { service: "email", Icon: Mail, text: "メールアドレスでログイン" },
こちらも同様にメールアドレスログインができなかった

2023-01-05 13:34 UTC, iikyara commented on src/pages/Start/hooks/useStartState.ts
> +  }, []);
ログイン済みならログインページ飛ばすという処理とかどうでしょうか
ログインページに入ったら強制ログアウトはUX的に悪そう

2023-01-05 15:28 UTC, teruto725 commented
ここでできるかなと思ってたんだが...
```
    const provider =
      accountService == "google"
        ? new firebase.auth.GoogleAuthProvider()
        : accountService == "email"
        ? new firebase.auth.EmailAuthProvider()
        : accountService == "twitter"
        ? new firebase.auth.TwitterAuthProvider()
        : accountService == "facebook"
        ? new firebase.auth.FacebookAuthProvider()
        : undefined;
```

2023-01-06 05:00 UTC, teruto725 commented
メールアドレスログイン実装しました！！

2023-01-06 05:08 UTC, merged