ignore-micro-cms-error
CodeParty2021/code_party_front pull request #97
Opened 2022-07-10 04:32 UTC by teruto725

MicroCMSのコンテンツが存在しないときエラーが表示されるようになっていた。
現状のコンテンツが見れなくなっていたので上の仕様を修正した

2022-07-11 08:51 UTC, iikyara requested changes
1点修正お願いします！

2022-07-11 08:51 UTC, iikyara commented on src/pages/Code/Coding/hooks/useCodeHooks.tsx
> +  }, [error, errorCodeAPI]);
以前のPRのチェック漏れだと思うんだけど，errorを指定したuseEffect内でsetErrorしちゃうと，useEffectがループしてクラッシュしそう（僕の環境では画面が真っ白になった）
以下のコードを別で書くとよさそう．
```
useEffect(() => {
  if (errorCodeAPI) {
    setError(errorCodeAPI);
  } else {
    setError(errorCodeAPI);
  }
}, [errorCodeAPI]);
```

2022-07-13 10:24 UTC, teruto725 commented on src/pages/Code/Coding/hooks/useCodeHooks.tsx
> +  }, [error, errorCodeAPI]);
おーほんとだ、ありがとう。修正します。

2022-07-13 10:26 UTC, teruto725 commented
修正したのでレビューお願いします。

2022-07-13 10:59 UTC, teruto725 commented
すまん！理解しきれてなかった。確認します！

2022-07-13 11:12 UTC, iikyara approved these changes
完璧だと思う！修正ありがとう！LGTM！

2022-07-13 11:12 UTC, merged